Repository hoprnet/hopr-utils, pull requests merged in 2020-08, with the labels that each got.

#26 bump version
  .github/workflows/nodejs.yml
  package.json
Labels: Patch Version, merge when passing

#27 Node version
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
  .nvmrc
  .yvmrc
  package.json
  src/collection/randomSubset.spec.ts
  src/collection/randomSubset.ts
  src/randomInteger.spec.ts
  src/randomInteger.ts
  src/u8a/allocate.spec.ts
  yarn.lock
Labels: Patch Version, merge when passing

#29 Node version
  .github/workflows/build-test-and-release.yaml
  .github/workflows/create-release.yml
  .github/workflows/nodejs.yml
  .github/workflows/publish.yml
Labels: Minor Version

#33 ✨ Getting pubkeys from nodes
  .gitignore
  package.json
  src/libp2p/index.spec.ts
  src/libp2p/index.ts
  yarn.lock
Labels: Patch Version

#35 🩹 Patch to include libp2p utils
  .github/workflows/build-test-and-release.yaml
  src/index.ts
Labels: Patch Version
